# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GEpmToolUI.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QStatusBar, QToolButton,
    QWidget)

class Ui_GEpmTool(object):
    def setupUi(self, GEpmTool):
        if not GEpmTool.objectName():
            GEpmTool.setObjectName(u"GEpmTool")
        GEpmTool.resize(499, 587)
        self.actionReport = QAction(GEpmTool)
        self.actionReport.setObjectName(u"actionReport")
        self.actionPDF = QAction(GEpmTool)
        self.actionPDF.setObjectName(u"actionPDF")
        self.actionGuide = QAction(GEpmTool)
        self.actionGuide.setObjectName(u"actionGuide")
        self.actionAbout = QAction(GEpmTool)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionTool = QAction(GEpmTool)
        self.actionTool.setObjectName(u"actionTool")
        self.centralwidget = QWidget(GEpmTool)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 484, 100, 32))
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(10, 194, 431, 21))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(130, 484, 100, 32))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(250, 484, 100, 32))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 124, 121, 16))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 84, 113, 21))
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(10, 144, 431, 21))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 64, 71, 16))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 34, 113, 21))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 14, 81, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 174, 121, 16))
        self.toolButton_2 = QToolButton(self.centralwidget)
        self.toolButton_2.setObjectName(u"toolButton_2")
        self.toolButton_2.setGeometry(QRect(450, 194, 21, 21))
        self.toolButton = QToolButton(self.centralwidget)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(450, 144, 21, 21))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 254, 461, 221))
        self.plainTextEdit.setReadOnly(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 234, 81, 16))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(90, 230, 51, 25))
        self.onHoldBox = QCheckBox(self.centralwidget)
        self.onHoldBox.setObjectName(u"onHoldBox")
        self.onHoldBox.setGeometry(QRect(160, 10, 85, 20))
        self.bessBox = QCheckBox(self.centralwidget)
        self.bessBox.setObjectName(u"bessBox")
        self.bessBox.setGeometry(QRect(160, 30, 85, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 10, 91, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(360, 10, 121, 16))
        self.bessList = QPlainTextEdit(self.centralwidget)
        self.bessList.setObjectName(u"bessList")
        self.bessList.setGeometry(QRect(250, 30, 91, 111))
        self.bessList.setPlaceholderText(u"Input Asset")
        self.plainTextEdit_3 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setObjectName(u"plainTextEdit_3")
        self.plainTextEdit_3.setGeometry(QRect(360, 30, 91, 111))
        GEpmTool.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(GEpmTool)
        self.statusbar.setObjectName(u"statusbar")
        GEpmTool.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(GEpmTool)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 499, 30))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        GEpmTool.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.actionTool)
        self.menu_2.addAction(self.actionGuide)
        self.menu_2.addAction(self.actionAbout)

        self.retranslateUi(GEpmTool)

        QMetaObject.connectSlotsByName(GEpmTool)
    # setupUi

    def retranslateUi(self, GEpmTool):
        GEpmTool.setWindowTitle(QCoreApplication.translate("GEpmTool", u"MainWindow", None))
        self.actionReport.setText(QCoreApplication.translate("GEpmTool", u"Report", None))
        self.actionPDF.setText(QCoreApplication.translate("GEpmTool", u"PDF", None))
        self.actionGuide.setText(QCoreApplication.translate("GEpmTool", u"Guide", None))
        self.actionAbout.setText(QCoreApplication.translate("GEpmTool", u"About", None))
        self.actionTool.setText(QCoreApplication.translate("GEpmTool", u"Tool", None))
        self.pushButton.setText(QCoreApplication.translate("GEpmTool", u"Generate", None))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setPlaceholderText(QCoreApplication.translate("GEpmTool", u".../Preventive-Pending Report.xlsx", None))
        self.pushButton_3.setText(QCoreApplication.translate("GEpmTool", u"Output Folder", None))
        self.pushButton_2.setText(QCoreApplication.translate("GEpmTool", u"Quit", None))
        self.label_5.setText(QCoreApplication.translate("GEpmTool", u"Sample Report Path", None))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("GEpmTool", u"Phone number", None))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setPlaceholderText(QCoreApplication.translate("GEpmTool", u".../report_demo.xlsx", None))
        self.label_2.setText(QCoreApplication.translate("GEpmTool", u"Telephone", None))
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("GEpmTool", u"Name", None))
        self.label.setText(QCoreApplication.translate("GEpmTool", u"PM engineer", None))
        self.label_6.setText(QCoreApplication.translate("GEpmTool", u"Target File", None))
        self.toolButton_2.setText(QCoreApplication.translate("GEpmTool", u"...", None))
        self.toolButton.setText(QCoreApplication.translate("GEpmTool", u"...", None))
        self.label_7.setText(QCoreApplication.translate("GEpmTool", u"Log Window", None))
        self.pushButton_4.setText(QCoreApplication.translate("GEpmTool", u"Clear", None))
        self.onHoldBox.setText(QCoreApplication.translate("GEpmTool", u"On Hold", None))
        self.bessBox.setText(QCoreApplication.translate("GEpmTool", u"BESS", None))
        self.label_3.setText(QCoreApplication.translate("GEpmTool", u"BESS Asset list", None))
        self.label_4.setText(QCoreApplication.translate("GEpmTool", u"PM DurTime Rule", None))
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setPlaceholderText(QCoreApplication.translate("GEpmTool", u"Unused Default PM Exp Time        12 Months Defibrillator   6 Months", None))
        self.menu.setTitle(QCoreApplication.translate("GEpmTool", u"Start", None))
        self.menu_2.setTitle(QCoreApplication.translate("GEpmTool", u"Help", None))
    # retranslateUi

